// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import 'dotenv/config'; // .env 변수를 강제로 먼저 읽어들임
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "libs/database/prisma/schema.prisma", // prisma.config.ts에 작성된 기준 경로와 터미널의 현재 실행 위치가 어긋나면 에러남
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
