/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Co-Panion BE API
 * (co-panion) 시스템 백엔드 API 명세서
 * OpenAPI spec version: 1.0
 */
import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

export const getAppControllerGetHelloV1MockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/v1",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};
export const getAppMock = () => [getAppControllerGetHelloV1MockHandler()];
