/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Co-Panion BE API
 * (co-panion) 시스템 백엔드 API 명세서
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../axios-instance";

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type appControllerGetHelloV1Response200 = {
  data: void;
  status: 200;
};

export type appControllerGetHelloV1ResponseSuccess =
  appControllerGetHelloV1Response200 & {
    headers: Headers;
  };
export type appControllerGetHelloV1Response =
  appControllerGetHelloV1ResponseSuccess;

export const getAppControllerGetHelloV1Url = () => {
  return `/api/v1`;
};

export const appControllerGetHelloV1 = async (
  options?: RequestInit,
): Promise<appControllerGetHelloV1Response> => {
  return customInstance<appControllerGetHelloV1Response>(
    getAppControllerGetHelloV1Url(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getAppControllerGetHelloV1QueryKey = () => {
  return [`/api/v1`] as const;
};

export const getAppControllerGetHelloV1QueryOptions = <
  TData = Awaited<ReturnType<typeof appControllerGetHelloV1>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof appControllerGetHelloV1>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAppControllerGetHelloV1QueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof appControllerGetHelloV1>>
  > = ({ signal }) => appControllerGetHelloV1({ signal });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof appControllerGetHelloV1>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AppControllerGetHelloV1QueryResult = NonNullable<
  Awaited<ReturnType<typeof appControllerGetHelloV1>>
>;
export type AppControllerGetHelloV1QueryError = unknown;

export function useAppControllerGetHelloV1<
  TData = Awaited<ReturnType<typeof appControllerGetHelloV1>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof appControllerGetHelloV1>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerGetHelloV1>>,
          TError,
          Awaited<ReturnType<typeof appControllerGetHelloV1>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAppControllerGetHelloV1<
  TData = Awaited<ReturnType<typeof appControllerGetHelloV1>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof appControllerGetHelloV1>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerGetHelloV1>>,
          TError,
          Awaited<ReturnType<typeof appControllerGetHelloV1>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAppControllerGetHelloV1<
  TData = Awaited<ReturnType<typeof appControllerGetHelloV1>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof appControllerGetHelloV1>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAppControllerGetHelloV1<
  TData = Awaited<ReturnType<typeof appControllerGetHelloV1>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof appControllerGetHelloV1>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAppControllerGetHelloV1QueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
